/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
object problem2 {
  def main(args: Array[String]) {
  	var num1: Long = 1 
  	var num2: Long = 2 
  	var temp: Long = 0 
  	val limit: Int = 4000000 
  	var accum: Long = num2 
  	while (num2 < limit) { 
  	  temp = num2 
  		num2 += num1 
  		num1 = temp 
  		if (num2 % 2 == 0) accum += num2 
  	} 
  println("accum: " + accum) 
  }
}
